# Generated by Django 3.2.4 on 2021-06-16 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Membership Picture')),
                ('free_delivery', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('first_order_disc', models.IntegerField(default=0, verbose_name='First Order Discount')),
                ('overall_discount', models.IntegerField(default=0)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Med', 'Medium'), ('Low', 'Low')], help_text='Priority of announcements', max_length=10)),
                ('q_gift', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quarterly Gift')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeCustomerId', models.CharField(max_length=255)),
                ('stripeSubscriptionId', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
