# Generated by Django 3.2.4 on 2021-06-16 18:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Delivery Type')),
                ('dispatch_speed', models.IntegerField(verbose_name='days to dispatch order')),
                ('delivery_speed', models.IntegerField(verbose_name='days to deliver order')),
                ('limit', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='order amount limit for set delivery cost')),
                ('const', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='set delivey cost')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='delivery rate')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=uuid.uuid4, editable=False, max_length=36)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('full_name', models.CharField(default='', editable=False, max_length=70)),
                ('phone_number', models.CharField(default=0, max_length=16, validators=[django.core.validators.RegexValidator(message="Enter phone number in a format: '+111111111' and no longer that 15 digits.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=85, verbose_name='city or town')),
                ('region', models.CharField(blank=True, max_length=85, null=True, verbose_name='region or county')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postcode', models.CharField(max_length=10, verbose_name='post/zip code')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('dispatch_date', models.DateTimeField(blank=True, null=True, verbose_name='order dispatched on')),
                ('est_dispatch_dte', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='estimated order dispatch date')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='order delivered on')),
                ('est_deliery_dte', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='estimated order delivery date')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('original_cart', models.TextField(default='')),
                ('stripe_pid', models.CharField(default='', max_length=254)),
                ('delivery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.deliverytype')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_orders', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_line', to='checkout.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
